In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("/home/jamesrunnalls/git/thetis/data/Level0/Decimated_Resolution_txt/00314868_ACD_ACS.txt", sep='\t', skiprows=9, header=None, error_bad_lines=False)
cols = ["Timestamp (s)","Depth (dbar)", "Depth Timestamp (s)", "serial #", "on secs", "num wvl", "C ref dark", "C ref counts*num wvl", "C sig dark", "C sig counts*num wvl", "A ref dark", "A ref counts*num wvl", "A sig dark", "A sig counts*num wvl", "ext temp counts", "int temp counts", "pressure counts"]
df.columns = cols + list(range(0, len(df.columns) - len(cols)))
df = df[df['on secs'].notna()]

FileNotFoundError: [Errno 2] No such file or directory: '/home/jamesrunnalls/git/thetis/data/Level0/Decimated_Resolution_txt/00314868_ACD_ACS.txt'

In [69]:
10 - np.nan

nan

In [20]:
df = pd.read_csv("/home/jamesrunnalls/git/thetis/calibration/HPE557A.cal", delim_whitespace=True, skiprows=31, 
                 header=None, error_bad_lines=False, skipfooter=20)
df.columns = []

/home/jamesrunnalls/anaconda3/envs/thetis/lib/python3.7/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

In [21]:
df

      0       1             2    3   4    5     6
0    ED  305.21  'uW/cm^2/nm'  2.0  BU  0.0  NONE
1    ED  308.56  'uW/cm^2/nm'  2.0  BU  0.0  NONE
2    ED  311.91  'uW/cm^2/nm'  2.0  BU  0.0  NONE
3    ED  315.27  'uW/cm^2/nm'  2.0  BU  0.0  NONE
4    ED  318.62  'uW/cm^2/nm'  2.0  BU  0.0  NONE
..   ..     ...           ...  ...  ..  ...   ...
312  ED  887.52  'uW/cm^2/nm'  2.0  BU  0.0  NONE
313  ED  890.77  'uW/cm^2/nm'  2.0  BU  0.0  NONE
314  ED  894.02  'uW/cm^2/nm'  2.0  BU  0.0  NONE
315  ED  897.26  'uW/cm^2/nm'  2.0  BU  0.0  NONE
316  ED  900.51  'uW/cm^2/nm'  2.0  BU  0.0  NONE

[317 rows x 7 columns]

In [35]:
file = "/home/jamesrunnalls/git/thetis/calibration/HPE557A.cal"

In [57]:
data = []
with open(file) as f:
    lines = list(f)
    for idx, line in enumerate(lines):
        if "uW/cm^2/nm" in line:
            if "OPTIC3" in line:
                line_arr = line.replace("\n", "").split(" ") + lines[idx + 1].replace("\n", "").split("\t")
            else:
                line_arr = line.replace("\n", "").split(" ") + [np.nan] * 4
            data.append(line_arr)
df = pd.DataFrame(data, columns=["ED", "val", "unit", "no1", "BU", "no2", "type", "a0", "a1", "Im", "Cint"])

In [63]:
a0 = np.array(df["a0"]).astype("float")
a1 = np.array(df["a1"]).astype("float")
Im = np.array(df["Im"]).astype("float")
Cint = np.array(df["Cint"]).astype("float")

In [61]:
a0

array([    nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan, 823.941,
       820.882, 821.191, 820.75 , 823.353, 817.456, 823.118, 819.162,
       820.176, 820.397, 821.382, 823.779, 819.015, 821.324, 820.456,
       818.882, 815.368, 820.529, 821.015, 819.618, 821.368, 821.353,
       817.456, 819.632, 822.897, 823.397, 822.794, 822.515, 823.559,
       823.324, 819.338, 822.412, 822.809, 819.294, 825.853, 824.471,
       821.324, 825.324, 823.   , 822.471, 826.632, 821.897, 819.029,
       822.485, 820.676, 821.529, 822.397, 818.147, 823.074, 820.882,
       818.588, 821.985, 820.176, 823.191, 824.176, 824.088, 820.941,
       824.882, 819.912, 818.794, 821.544, 818.471, 822.088, 823.059,
       819.485, 821.515, 819.044, 821.221, 821.809, 820.618, 821.059,
       817.529, 819.529, 819.588, 821.882, 820.441, 821.074, 821.882,
       821.   , 821.412, 819.662, 821.074, 821.162, 821.912, 819.529,
       822.176, 820.368, 818.985, 820.691, 821.853, 822.588, 817.603,
       817.971, 822.059, 818.162, 818.912, 819.868, 818.103, 819.647,
       819.338, 818.118, 817.353, 821.824, 818.897, 816.574, 814.897,
       817.132, 816.853, 817.824, 820.059, 820.176, 817.603, 820.206,
       821.559, 819.676, 819.691, 822.544, 818.706, 817.603, 821.485,
       818.441, 821.088, 819.074, 817.088, 818.132, 818.926, 818.985,
       817.147, 815.809, 820.426, 819.265, 817.647, 818.471, 820.265,
       820.221, 819.324, 823.338,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan])

In [88]:
a = np.array([[2,3,2],[5,6,1]])
b = np.array([3,5])
c = a * b[:, None]

In [89]:
a

array([[2, 3, 2],
       [5, 6, 1]])

In [96]:
a[0, :]

array([2, 3, 2])

In [67]:
c

array([[ 6,  9,  6],
       [25, 30,  5]])

In [68]:
b[:, None]

array([[3],
       [5]])

In [72]:
x = np.full([5,2], np.nan)
x

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [73]:
x[:,0]

array([nan, nan, nan, nan, nan])

In [74]:
np.nan - 0

nan

In [49]:
file = "/Users/camil/Documents/GitRepos/ThetisDatalakes/thetis-vertical-profiler/calibration/acs286.dev"

In [82]:
import pandas as pd
import numpy as np
import os
from operator import itemgetter


file = "/Users/camil/Documents/GitRepos/ThetisDatalakes/thetis-vertical-profiler/calibration/acs286.dev"


wC_wA_C0_A0 = []
C_corr = []
A_corr = []

with open(file) as f:
    lines = list(f)
    for idx, line in enumerate(lines):
        if "tcal" in line:
            t_cal = line.replace("\n", "").split(" ")
        if "number of temperature bins" in line:
            l_n_t_bins = line.replace("\t", "").split(";")
            n_t_bins = int(l_n_t_bins[0])
        if "temperature bins" in line:
            l_t_bins = line.split("\t")
        if "C and A offset, and C and A temperature correction info" in line:
            char_to_replace = {'C': '',
                               'A': ''}
            for key, value in char_to_replace.items():
                line = line.replace(key, value)
            
            line_arr = line.replace("\n", "").split("\t")
            
            wC_wA_C0_A0.append(itemgetter(0,1,3,4)(line_arr))
            C_corr_temp = list(map(float, np.transpose(line_arr[6:6+n_t_bins-1])))
            A_corr_temp = list(map(float, np.transpose(line_arr[7+n_t_bins:7+2*n_t_bins-1])))
            C_corr.append(C_corr_temp)
            A_corr.append(A_corr_temp)
            
tcal = float(t_cal[1])
ical = float(t_cal[4])
t_bins = list(map(float, l_t_bins[5:5+n_t_bins]))

df = pd.DataFrame(wC_wA_C0_A0, columns=["wC", "wA", "C0", "A0"])

C_corr = np.array(C_corr).astype("float")
A_corr = np.array(A_corr).astype("float")
landa_C = np.array(df["wC"]).astype("float")
C0 = np.array(df["C0"]).astype("float")
landa_A = np.array(df["wA"]).astype("float")
A0 = np.array(df["A0"]).astype("float")

In [83]:
df

       wC     wA         C0         A0
0   400.1  398.5    -1.1268   0.031727
1   403.9  402.6  -0.967835   0.138826
2   407.5  406.2  -0.829249   0.225513
3   411.0  409.6  -0.701859   0.297068
4   414.6  413.2  -0.584462   0.360795
..    ...    ...        ...        ...
76  723.7  723.2  -0.373119   0.618488
77  727.6  727.2  -0.627906   0.369199
78  731.8  731.0  -0.887958   0.110622
79  735.3  734.8  -1.118503  -0.122754
80  739.4  738.5  -1.295139  -0.303711

[81 rows x 4 columns]

In [84]:
def read_acs_calibration_data(file):
    wC_wA_C0_A0 = []
    C_corr = []
    A_corr = []

    with open(file) as f:
        lines = list(f)
        for idx, line in enumerate(lines):
            if "tcal" in line:
                t_cal = line.replace("\n", "").split(" ")
            if "number of temperature bins" in line:
                l_n_t_bins = line.replace("\t", "").split(";")
                n_t_bins = int(l_n_t_bins[0])
            if "temperature bins" in line:
                l_t_bins = line.split("\t")
            if "C and A offset, and C and A temperature correction info" in line:
                char_to_replace = {'C': '',
                               'A': ''}
                for key, value in char_to_replace.items():
                    line = line.replace(key, value)
                line_arr = line.replace("\n", "").split("\t")
                wC_wA_C0_A0.append(itemgetter(0,1,3,4)(line_arr))
                C_corr_temp = list(map(float, np.transpose(line_arr[6:6+n_t_bins-1])))
                A_corr_temp = list(map(float, np.transpose(line_arr[7+n_t_bins:7+2*n_t_bins-1])))
                C_corr.append(C_corr_temp)
                A_corr.append(A_corr_temp)
            
    tcal = float(t_cal[1])
    ical = float(t_cal[4])
    t_bins = list(map(float, l_t_bins[5:5+n_t_bins]))
    
    df = pd.DataFrame(wC_wA_C0_A0, columns=["wC", "wA", "C0", "A0"])
    
    C_corr = np.array(C_corr).astype("float")
    A_corr = np.array(A_corr).astype("float")
    landa_C = np.array(df["wC"]).astype("float")
    C0 = np.array(df["C0"]).astype("float")
    landa_A = np.array(df["wA"]).astype("float")
    A0 = np.array(df["A0"]).astype("float")
    return tcal, ical, t_bins, landa_C, landa_A, C0, A0, C_corr, A_corr

In [85]:
import pandas as pd
import numpy as np
import os
import re
import sys
import glob
import math
import statistics
import matplotlib.pyplot as plt
import datetime as dt
from datetime import datetime, timezone
from copy import deepcopy
import json

calibration_dir = "/Users/camil/Documents/GitRepos/ThetisDatalakes/thetis-vertical-profiler/calibration/"

with open(os.path.join(calibration_dir, "calibration.json"), "r") as f:
    calibration = json.load(f)
    tcal, ical, t_bins, landa_C, landa_A, C0, A0, C_corr, A_corr = read_acs_calibration_data(os.path.join(calibration_dir, "acs380.dev"))

In [87]:
read_acs_calibration_data(os.path.join(calibration_dir, "acs380.dev"))

(22.3,
 19.6,
 [0.916045,
  1.228939,
  2.431034,
  3.4845,
  4.549524,
  5.4832,
  6.507391,
  7.466,
  8.498,
  9.4936,
  10.496667,
  11.497917,
  12.484348,
  13.486667,
  14.496,
  15.51,
  16.4912,
  17.50087,
  18.509565,
  19.498333,
  20.503913,
  21.539643,
  22.448182,
  23.531739,
  24.431333,
  25.5025,
  26.54,
  27.449545,
  28.554167,
  29.438214,
  30.505263,
  31.538438,
  32.4625,
  33.584516,
  34.406538],
 array([400.9, 403.7, 406.6, 410. , 412.8, 416. , 419.4, 423.3, 427.6,
        431.7, 434.8, 438.4, 442.3, 446.3, 450.9, 455. , 458.9, 462.7,
        466.9, 471.5, 476.4, 481. , 485.3, 489.7, 493.5, 497.7, 501.2,
        505.5, 510.4, 515.1, 519.7, 524.2, 528. , 531.7, 535.6, 539.4,
        543.8, 548. , 552.1, 556.2, 560.8, 565. , 569.1, 573.4, 577.1,
        581.2, 585.2, 588.5, 592.7, 596.6, 600.8, 605.3, 609.2, 613.7,
        618. , 622.4, 626.4, 630.9, 634.5, 638.8, 643. , 647.3, 651.6,
        656. , 660.6, 665.2, 669.5, 673.9, 678.3, 682.4, 686.1, 690.2,
        693.7, 697.6, 701.2, 704.9, 708.9, 712.6, 716.8, 720.1, 724.3,
        727.5, 732.7, 735.4]),
 array([400.3, 403. , 405.9, 408.9, 411.9, 414.9, 418.5, 422.6, 426.3,
        430.1, 434. , 437.1, 441. , 445.3, 449.2, 453.4, 457.4, 461.1,
        465. , 469.4, 474.1, 478.9, 483.4, 487.6, 491.4, 494.9, 499.1,
        503.4, 507.6, 512.5, 517.1, 522. , 525.6, 529.6, 533.4, 537.3,
        541.3, 545.6, 549.5, 554. , 558.1, 562.7, 566.8, 570.7, 574.7,
        578.6, 582.5, 585.4, 588.6, 592.7, 597.1, 600.8, 605.1, 609.3,
        613.7, 618.2, 622.4, 626.4, 630.5, 634.4, 638.3, 642.5, 646.9,
        651.1, 655.5, 660. , 664.7, 669. , 673.2, 677.5, 681.7, 685.6,
        689.3, 693.1, 696.8, 700.4, 704.2, 708.1, 711.3, 715.2, 719.3,
        723.3, 727.2, 731.9]),
 array([ 0.873275,  0.9     ,  0.936955,  0.974161,  0.997163,  1.030954,
         1.043426,  1.070862,  1.090819,  1.123065,  1.140462,  1.153403,
         1.170087,  1.193954,  1.211681,  1.227823,  1.242954,  1.243839,
         1.262437,  1.280487,  1.29558 ,  1.307558,  1.314658,  1.329461,
         1.338175,  1.353718,  1.358423,  1.358646,  1.367692,  1.365414,
         1.376724,  1.381564,  1.388626,  1.389609,  1.394804,  1.39824 ,
         1.396039,  1.408643,  1.406344,  1.405857,  1.407626,  1.410825,
         1.406773,  1.400693,  1.395188,  1.387638,  1.376971,  1.362326,
         1.34352 ,  1.322763,  1.296931,  1.282032,  1.269132,  1.263185,
         1.261252,  1.25802 ,  1.255314,  1.256464,  1.250322,  1.249469,
         1.239842,  1.236741,  1.220912,  1.209493,  1.196158,  1.18573 ,
         1.176043,  1.170553,  1.155875,  1.141168,  1.118824,  1.085805,
         1.044539,  0.989598,  0.92479 ,  0.840621,  0.736121,  0.60499 ,
         0.448788,  0.26576 ,  0.050764, -0.158613, -0.424842, -0.643955]),
 array([0.346465, 0.422323, 0.484085, 0.529328, 0.564486, 0.59676 ,
        0.624148, 0.649284, 0.673978, 0.699877, 0.722958, 0.747137,
        0.771729, 0.793461, 0.818451, 0.843177, 0.866638, 0.89305 ,
        0.918667, 0.944298, 0.969768, 0.994656, 1.019591, 1.044099,
        1.067   , 1.089595, 1.110503, 1.130989, 1.150205, 1.170803,
        1.191231, 1.212421, 1.232595, 1.253037, 1.272774, 1.291872,
        1.311606, 1.328061, 1.345577, 1.362345, 1.380434, 1.396338,
        1.412219, 1.426288, 1.436829, 1.443843, 1.445311, 1.444518,
        1.442731, 1.435904, 1.426737, 1.419217, 1.416808, 1.420893,
        1.429938, 1.441268, 1.453163, 1.465045, 1.47633 , 1.486832,
        1.495745, 1.502981, 1.507075, 1.508957, 1.508784, 1.508485,
        1.509893, 1.513115, 1.51577 , 1.515808, 1.509902, 1.497484,
        1.476653, 1.44488 , 1.401252, 1.343429, 1.268461, 1.175527,
        1.060467, 0.916511, 0.74502 , 0.552655, 0.330442, 0.09073 ]),
 array([[ 0.031591,  0.03388 ,  0.031642, ..., -0.008484, -0.009923,
         -0.011377],
        [ 0.03143 ,  0.032446,  0.030716, ..., -0.007606, -0.008793,
         -0.010405],
        [ 0.029891,  0.030604,  0.028148, ..., -0.006713, -0.008533,
         -0.009354],
        ...,
        [-0.007377, -0.006618, -0.005755, ...,  0.000518,  0.000461,
          0.000453],
        [-0.006244, -0.00573 , -0.004986, ...,  0.000499,  0.000396,
          0.000393],
        [-0.006639, -0.005961, -0.005243, ...,  0.000453,  0.00039 ,
          0.000181]]),
 array([[-4.5535e-02, -4.5350e-02, -4.5112e-02, ...,  8.2510e-03,
          7.9690e-03,  9.7100e-03],
        [-4.1567e-02, -4.1086e-02, -4.0069e-02, ...,  7.2120e-03,
          7.1450e-03,  7.7430e-03],
        [-3.8643e-02, -3.7179e-02, -3.6263e-02, ...,  5.8990e-03,
          5.2410e-03,  6.5690e-03],
        ...,
        [-1.2497e-02, -9.9780e-03, -8.8880e-03, ...,  1.8000e-04,
          1.6000e-05,  8.0000e-06],
        [-1.2384e-02, -9.8910e-03, -8.8620e-03, ...,  6.4000e-05,
         -1.3200e-04, -1.1700e-04],
        [-1.2342e-02, -9.8460e-03, -8.8350e-03, ..., -3.2000e-05,
         -7.7000e-05, -1.3700e-04]]))

In [ ]:


tab_corr.to_numpy()